### ISSUE TITLE
Run question.

### ISSUE THREAD

**Issue by JamesXu20150314** [ttrouill/complex#1]
Hello,

I have do all steps by your readme file.

However, I have encountered an question as follows:

![image](https://cloud.githubusercontent.com/assets/11470231/21961200/8a32e0c4-db3e-11e6-8452-0e9b2b435913.png)

Could you help me solve this problem?

Thank you.

James.

**Comment by ttrouill** [comment]
Hi James,

Sure, first which version of python are you using?
And second can you run:

$ pip freeze | grep downhill

And tell me which version of downhill you have installed?

Cheers,
Théo

2017-01-15 9:21 GMT+01:00 ZhiminXu <notifications@github.com>:

**Comment by leonardomra** [comment]
Hi Théo,
I have the same problem. I'm running Python 2.7.10  and downhill 0.4.0
Thanks,
Leonardo

**Comment by ttrouill** [comment]
Hi guys,

Sorry for the latency, it seems a few things have moved in the last version of downhill, 
I don't have time to explore that in details for the moment 
so reverting to the previous version will do the trick.
Simply update your copy of the repo and re-run:

`pip install -r requirements.txt`

Cheers,
Théo
