### ISSUE TITLE
will it work on windows?

### ISSUE THREAD

**Issue by Sandy4321** [ttrouill/complex#10]
will it work on windows?

**Comment by ttrouill** [comment]
Mmmh don't see any reason why it should not, give it a try and come back tell us! :)

**Comment by Yongquan-He** [comment]
Dear author,I'm a Chinense student, after I train on my data.  I achieve a .mat model. It's a entities_num*dimension Matrix. But I don't know how the row corresponding to the entity. I just learn python recently. and I love read paper. This was my first time to practice experiment. Sorry for bother you about my simple question.
