### ISSUE TITLE
a beginner's question

### ISSUE THREAD

**Issue by Yongquan-He** [ttrouill/complex#12]
Dear author,I'm a Chinenese student, after I train on my data. I achieve a .mat model. It's a entities_num*dimension Matrix. But I don't know how the row corresponding to the entity. I just learn python recently. and I love read paper. This was my first time to practice experiment. Sorry for bother you about my simple question.

**Comment by ttrouill** [comment]
Hi!
No worries! It's true that the entity names are not exported, you can find them very easily in the dictionary `fb15kexp.entities_dict` , where the entity row numbers are indexed by their names.

**Comment by Yongquan-He** [comment]
Thanks for your reply!
