### ISSUE TITLE
Regarding implementing constraints of TransR inside your code

### ISSUE THREAD

**Issue by navdeepkjohal** [ttrouill/complex#15]
Hello Theo,

I am trying to implement TransR model using your code which, as you know, has the objective function ||hMr + r - tMr||\_{2} for a given relation r(h,t). Further, as you know, this model requires that we put constraints ||hMr||\_{2} <= 1, ||tMr||\_{2} <=1 and ||r||\_{2} <=1 on the objective function.
If I take a look at the other codes for TransR, for example here ([https://github.com/thunlp/OpenKE/blob/master/models/TransR.py])  They are taking L2 norm hMr/||hMr||\_{2}, tMr/||tMr||\_{2}  and r/||r||\_{2} to implement the above constraints on the objective function before visiting mini-batch.

Could you please tell how can i implement the above constraints as hMr/||hMr||\_{2}, tMr/||tMr||\_{2}  and r/||r||\_{2}  inside your code. I am getting confused because in your code h and Mr would be stored separately and I can only implement an objective function self.loss with both h and Mr present separately in it.  

(a)	Here is one solution according to me: i implement a class TransR_Batch_Loader(Batch_Loader) inside batching.py where it computes h = h/sqrt(L2_norm(hMr)) and Mr = Mr/sqrt(L2_norm(hMr)) separately inside the __call__() function and save these parameters back in the model (like in line 81 of batching.py in your code). I can do similar thing for ||hMr||\_{2} and with ||r||\_{2}, the constraint is straight-forward.  Afterwards, when the batch index of h, Mr is separately passed to the optimization algorithm, the algorithm is optimizing hMr = h/sqrt(L2_norm(hMr))*Mr/sqrt(L2_norm(hMr)) = hMr/L2_norm(hMr) in self.loss of Model. Can you please tell me if this is the right way of projecting hMr, tMr and r to unit l2-ball before visiting each mini-batch?

(b)	 Can you please suggest any other way of putting the above constraints in TransR model?

Best
Navdeep

**Comment by ttrouill** [comment]
Hi Navdeep,

That's exactly the way I would do it! Don't forget to override the `get_loss_args_and_symb_vars` function in your model class to use your custom batch loader (see in TransE models). Also if you want a faster computation of the ranking metrics, you can implement a specific version of the TransR scoring function that will compute scores on all objects/subjects at a time, have a look at the `compute_scores` function in `evaluation.py` where it's done for other models.

Tell me if it works!
