### ISSUE TITLE
Question about concatenation in extract_sub_scores function.

### ISSUE THREAD

**Issue by gsp2014** [ttrouill/complex#6]
Hi Théo,

I wonder if this line https://github.com/ttrouill/complex/blob/61fa3f6bf424aa284b467977317d0f7f17647d3a/efe/evaluation.py#L88 should be "res = Result(res.preds[idxs], res.true_vals[idxs], res.ranks[np.concatenate((idxs, len(idxs)+idxs))], res.raw_ranks[np.concatenate((idxs, len(idxs)+idxs))])". That is, add len(idxs) to the concatenation.

Thanks a lot.

**Comment by ttrouill** [comment]
Indeed it should be this, will fix asap, thanks!

**Comment by ttrouill** [comment]
Actually no! Because `idxs` is a boolean array that has the same size as `self.ranks`, and is equal to `True` at the indexes to extract, so the correct code is indeed `np.concatenate((idxs,idxs))`. 

Sorry for the latency and the wrong first reply :/

**Comment by ttrouill** [comment]
Actually no! Because `idxs` is a boolean array that has the same size as `self.ranks`, and is equal to `True` at the indexes to extract, so the correct code is indeed `np.concatenate((idxs,idxs))`. 

Sorry for the latency and the wrong first reply :/

**Comment by gsp2014** [comment]
Yes, it's my fault. Thanks for your patience!
