### ISSUE TITLE
Downhill version 0.3.2 not working anymore

### ISSUE THREAD

**Issue by GittiHab** [ttrouill/complex#8]
As downhill v0.3.2 depends on the package `climate` that does not seem to exist anymore, the repo can not be installed anymore.

I have just checked v0.4.0 of downhill and it seems to mainly have changed the logging part, i.e., removed the dependency to `climate`.

Therefore, commenting out the 4th line in `*_run.py` (`downhill.base.logging.setLevel(20)`) seems to do the trick and resolve the issue with #1.

**Comment by ttrouill** [comment]
Sorry again for the latency, thanks for investigating into this!
I updated the repo, tested quickly, looks like it works :)
