### ISSUE TITLE
Writing out the scores

### ISSUE THREAD

**Issue by GittiHab** [ttrouill/complex#9]
Hi, I must admit that I have been finding the code to confusing to solve this myself.

How would I go about, if I would like to write out the predicted scores of the models into a file for further use? I require the actual predicted triples/heads/tails for a given test triple with their scores (with this the ranks can be derived).

Thank you!

**Comment by ttrouill** [comment]
Hi!
Sorry for the super long latency, indeed it's the not-so-elegant part of the code, for performance reasons.
I guess you found your answer in the meantime, if not, it was in this already closed issue: https://github.com/ttrouill/complex/issues/7

**Comment by ttrouill** [comment]
Hi!
Sorry for the super long latency, indeed it's the not-so-elegant part of the code, for performance reasons.
I guess you found your answer in the meantime, if not, it was in this already closed issue: https://github.com/ttrouill/complex/issues/7
